name: Auto Merge Green PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Enable auto-merge
        run: |
          gh pr merge "$PR_URL" --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.PR_CREATOR_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}